### ISSUE TITLE
Beyanname hep nul geliyor

### ISSUE THREAD

**Issue by esero** [gokmenyilmaz/EF7_RC0_TEST#7]
bu bir sorun mu?

**Comment by esero** [comment]
bekliyorum

**Comment by gokmenyilmaz** [comment]
Kontrol ettim sorunu saba atıyorum düzelt bug bul haber ver

**Comment by esero** [comment]
sorunları hallettim kontrol edip kapatabilirsiniz

**Comment by gokmenyilmaz** [comment]
Kapatıyorum. Aferin sana...
